name: valarpay
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.3.0+6

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  path: ^1.9.1
  go_router: ^14.2.0
  flutter_riverpod: ^2.5.1
  file_picker: ^10.1.0
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.3
  url_launcher: ^6.2.2
  flutter_native_splash: ^2.4.4
  flutter_svg: ^2.0.9
  smooth_page_indicator: ^1.0.0+2
  intl: ^0.20.2
  qr_flutter: ^4.1.0
  fluttertoast: ^8.2.8
  dio: ^5.9.0
  device_info_plus: ^10.1.0
  network_info_plus: ^6.0.1
  local_auth: ^2.2.0
  flutter_secure_storage: ^9.0.0
  sms_autofill: ^2.4.0
  permission_handler: ^11.0.1
  image_picker: ^1.1.2
  mobile_scanner: ^6.0.0
  qr_code_tools: ^0.2.0
  camera: ^0.10.5+9
  path_provider: ^2.1.4
  image: ^4.0.17
  google_mlkit_text_recognition: ^0.14.0
  nigerian_states_and_lga: ^1.0.0
  flutter_contacts: ^1.1.9+2
  connectivity_plus: ^6.0.5
  screenshot: ^3.0.0
  share_plus: ^12.0.1
  flutter_image_compress: ^2.4.0
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^18.0.1
  package_info_plus: ^8.1.2
  shimmer: ^3.0.0
  socket_io_client: ^3.1.4
  smile_id: ^11.2.8
  google_mlkit_face_detection: ^0.12.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^5.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/gifs/
    - assets/images/
    - assets/images/payment_wid/
    - assets/images/nav_icons/
    - assets/images/service_icon/
    - assets/images/me_icons/
    - assets/images/investment/
    # - assets/fonts/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package


flutter_native_splash:
# This package generates native code to customize Flutter's default white native splash screen
# with background color and splash image.
# Customize the parameters below, and run the following command in the terminal:
# dart run flutter_native_splash:create
# To restore Flutter's default white splash screen, run the following command in the terminal:
# dart run flutter_native_splash:remove

# IMPORTANT NOTE: These parameter do not affect the configuration of Android 12 and later, which
# handle splash screens differently that prior versions of Android.  Android 12 and later must be
# configured specifically in the android_12 section below.

# color or background_image is the only required parameter.  Use color to set the background
# of your splash screen to a solid color.  Use background_image to set the background of your
# splash screen to a png image.  This is useful for gradients. The image will be stretch to the
# size of the app. Only one parameter can be used, color and background_image cannot both be set.
color: "#f76008"
#background_image: "assets/background.png"

# Optional parameters are listed below.  To enable a parameter, uncomment the line by removing
# the leading # character.

# The image parameter allows you to specify an image used in the splash screen.  It must be a
# png file and should be sized for 4x pixel density.
#image: assets/splash.png

# The branding property allows you to specify an image used as branding in the splash screen.
# It must be a png file. It is supported for Android, iOS and the Web.  For Android 12,
# see the Android 12 section below.
#branding: assets/dart.png

# To position the branding image at the bottom of the screen you can use bottom, bottomRight,
# and bottomLeft. The default values is bottom if not specified or specified something else.
#branding_mode: bottom

# Set the branding padding from the bottom of the screen.  The default value is 0
# (Not supported on web yet)
# branding_bottom_padding: 24

# The color_dark, background_image_dark, image_dark, branding_dark are parameters that set the background
# and image when the device is in dark mode. If they are not specified, the app will use the
# parameters from above.  If there is no parameter above, the app will use the light mode values.
# If the image_dark parameter is specified, color_dark or background_image_dark must be specified.
# color_dark and background_image_dark cannot both be set.
color_dark: "#042a49"
#background_image_dark: "assets/dark-background.png"
#image_dark: assets/splash-invert.png
#branding_dark: assets/dart_dark.png

# From Android 12 onwards, the splash screen is handled differently than in previous versions.
# Please visit https://developer.android.com/guide/topics/ui/splash
# Following are specific parameters for Android 12+.
android_12:
  # The image parameter sets the splash screen icon image.  If this parameter is not specified,
  # the app's launcher icon will be used instead.
  # Please note that the splash screen will be clipped to a circle on the center of the screen.
  # App icon with an icon background: This should be 960×960 pixels, and fit within a circle
  # 640 pixels in diameter.
  # App icon without an icon background: This should be 1152×1152 pixels, and fit within a circle
  # 768 pixels in diameter.  To fit a 1152x1152 image within a circle with a 768 diameter, simply 
  # ensure that the most important design elements of your image are placed within a circular area
  # with a 768 diameter at the center of the 1152x1152 canvas.
  #image: assets/android12splash.png

  # Splash screen background color.
  color: "#f76008"

  # App icon background color.
  #icon_background_color: "#111111"

  # The branding property allows you to specify an image used as branding in the splash screen.
  #branding: assets/dart.png

  # The image_dark, color_dark, icon_background_color_dark, and branding_dark set values that
  # apply when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above.  If there is no parameter above, the app will use the light mode values.
  #image_dark: assets/android12splash-invert.png
  color_dark: "#042a49"
  #icon_background_color_dark: "#eeeeee"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
