import 'package:flutter/material.dart';
import 'package:valarpay/core/utils/color_utils.dart';

class ShareableTransactionReceiptDetail {
  final String label;
  final String value;
  final bool? isSuccessful;

  ShareableTransactionReceiptDetail({
    required this.label,
    required this.value,
    this.isSuccessful,
  });
}

class ShareableTransactionReceipt extends StatelessWidget {
  final List<ShareableTransactionReceiptDetail> transactionDetailList;
  final String date;

  const ShareableTransactionReceipt({
    super.key,
    required this.transactionDetailList,
    required this.date,
  });

  @override
  Widget build(BuildContext context) {
    final isDark = Theme.of(context).brightness == Brightness.dark;

    return Container(
      decoration: BoxDecoration(
        color: isDark ? Color(0XFF46352B) : Color(0XFFFFEEE3),
        borderRadius: BorderRadius.circular(12),
        boxShadow: [
          BoxShadow(color: Colors.black12, blurRadius: 8, spreadRadius: 2),
        ],
      ),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          // Header
          Container(
            padding: EdgeInsets.all(16),
            width: double.infinity,
            decoration: BoxDecoration(
              color: appTheme.primaryColor,
              borderRadius: BorderRadius.only(
                topLeft: Radius.circular(12),
                topRight: Radius.circular(12),
              ),
            ),
            child: Column(
              children: [
                Row(
                  mainAxisAlignment: MainAxisAlignment.spaceBetween,
                  children: [
                    Row(
                      children: [
                        ClipRRect(
                          borderRadius: BorderRadius.circular(4),
                          child: Image.asset(
                            'assets/images/logo.png',
                            height: 24,
                            fit: BoxFit.cover,
                          ),
                        ),
                        const SizedBox(width: 8),
                        const Text(
                          "ValarPay",
                          style: TextStyle(
                            fontSize: 16,
                            fontWeight: FontWeight.bold,
                            color: Colors.white,
                          ),
                        ),
                      ],
                    ),
                    const Text(
                      "Beyond Banking",
                      style: TextStyle(
                        fontWeight: FontWeight.w600,
                        color: Colors.white,
                      ),
                    ),
                  ],
                ),
                const SizedBox(height: 8),
                const Text(
                  "Transaction Receipt",
                  style: TextStyle(
                    fontSize: 16,
                    fontWeight: FontWeight.bold,
                    color: Colors.white,
                  ),
                ),
                SizedBox(
                  width: double.infinity,
                  child: Text(
                    "Generated by ValarPay on $date",
                    textAlign: TextAlign.center,
                    maxLines: 1,
                    overflow: TextOverflow.ellipsis,
                    style: const TextStyle(fontSize: 10, color: Colors.white),
                  ),
                ),
              ],
            ),
          ),
          const SizedBox(height: 5),

          Container(
            padding: EdgeInsets.all(16),
            child: Column(
              children: [_buildDetailsCard(context, transactionDetailList)],
            ),
          ),

          const SizedBox(height: 16),
          const Padding(
            padding: EdgeInsets.symmetric(horizontal: 16),
            child: Text(
              "Thank you for banking with ValarPay. For support, contact us at \n support@Valarpay.com, call +2342013309609 or Head Office: \n C3&C4 Suite 2nd Floor Ejison Plaza 9a New Market Road Main \n Market Onitsha",
              textAlign: TextAlign.left,
              style: TextStyle(fontSize: 11),
            ),
          ),
          const SizedBox(height: 25),
        ],
      ),
    );
  }

  Widget _buildDetailsCard(
    BuildContext context,
    List<ShareableTransactionReceiptDetail> details,
  ) {
    return Column(
      children:
          details.asMap().entries.map((entry) {
            final index = entry.key;
            final detail = entry.value;
            final isLast = index == details.length - 1;

            return Column(
              children: [
                _buildDetailRow(context, detail),
                if (!isLast) const SizedBox(height: 12),
              ],
            );
          }).toList(),
    );
  }

  Widget _buildDetailRow(
    BuildContext context,
    ShareableTransactionReceiptDetail detail,
  ) {
    String displayValue = detail.value;

    // For Transaction ID, show first 13 characters + ellipsis if too long
    if (detail.label.toLowerCase().contains('transaction id') &&
        detail.value.length > 13) {
      displayValue = '${detail.value.substring(0, 13)}...';
    }

    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 4),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(
            detail.label,
            style: const TextStyle(fontSize: 13, color: Colors.grey),
          ),
          Flexible(
            child: Text(
              displayValue,
              textAlign: TextAlign.end,
              maxLines: 1,
              overflow: TextOverflow.ellipsis,
              style: TextStyle(
                fontSize: 13,
                fontWeight: FontWeight.w500,
                color:
                    detail.label == 'Status'
                        ? detail.isSuccessful != null &&
                                detail.isSuccessful == true
                            ? Colors.green
                            : Colors.red
                        : null,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
